default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>

development:
  <<: *default
  database: lov3time_development

test:
  <<: *default
  database: lov3time_test

# NOT YET
# production:
#   url: <%= ENV["LOV3TIME_DATABASE_URL"] %>
